# Generated by Django 5.2.5 on 2025-08-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='pfp',
            field=models.ImageField(default='Images/default.png', max_length=255, upload_to='Images/'),
        ),
    ]
