# Generated by Django 5.2.5 on 2025-08-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSite', '0002_alter_user_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='pfp',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
